-- Security hardening migration
-- 1) Remove teller assumptions from role policy (data-level)
-- 2) Add admin security pin + forced password change
-- 3) Add PIN lockout tracking fields

-- USERS.ADMIN_PIN_HASH
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'ADMIN_PIN_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (ADMIN_PIN_HASH VARCHAR2(255))';
  END IF;
END;
/

-- USERS.FORCE_PASSWORD_CHANGE
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'FORCE_PASSWORD_CHANGE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (FORCE_PASSWORD_CHANGE NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- CUSTOMERS.PIN_FAILED_ATTEMPTS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'PIN_FAILED_ATTEMPTS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (PIN_FAILED_ATTEMPTS NUMBER(2) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- CUSTOMERS.PIN_LOCKED
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'PIN_LOCKED';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (PIN_LOCKED NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- CUSTOMERS.PIN_LOCKED_AT
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'PIN_LOCKED_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (PIN_LOCKED_AT TIMESTAMP NULL)';
  END IF;
END;
/

COMMIT;
