-- Card normalization and safety constraints
-- Goal: keep card data only in CARDS and enforce one active card per customer

-- Drop legacy encrypted card columns from ACCOUNTS if they still exist
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ACCOUNTS' AND COLUMN_NAME = 'CARD_NUMBER';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNTS DROP COLUMN CARD_NUMBER';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ACCOUNTS' AND COLUMN_NAME = 'CVV';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNTS DROP COLUMN CVV';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'ACCOUNTS' AND COLUMN_NAME = 'CARD_EXPIRY';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ACCOUNTS DROP COLUMN CARD_EXPIRY';
  END IF;
END;
/

-- Add FK CARDS.ACCOUNT_ID -> ACCOUNTS.ID if missing
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'CARDS'
    AND CONSTRAINT_TYPE = 'R'
    AND CONSTRAINT_NAME = 'FK_CARDS_ACCOUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CARDS ADD CONSTRAINT FK_CARDS_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID)';
  END IF;
END;
/

-- Enforce at most one active card (IS_ACTIVE=1) per customer
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'UQ_CARDS_ONE_ACTIVE_PER_CUSTOMER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_CARDS_ONE_ACTIVE_PER_CUSTOMER ON CARDS (CASE WHEN IS_ACTIVE = 1 THEN CUSTOMER_ID END)';
  END IF;
END;
/

COMMIT;
