-- User-scoped key metadata table (Phase 2 foundation)
-- NOTE: This script only creates metadata storage and does not alter existing encryption flows yet.

CREATE TABLE USER_KEY_METADATA (
  USER_ID VARCHAR2(36) PRIMARY KEY,
  KDF_ALGO VARCHAR2(32) DEFAULT 'pbkdf2-sha256' NOT NULL,
  KDF_ITERATIONS NUMBER(10, 0) DEFAULT 310000 NOT NULL,
  KDF_SALT_HEX VARCHAR2(128) NOT NULL,
  WRAPPED_DEK_B64 CLOB NOT NULL,
  KEY_VERSION NUMBER(10, 0) DEFAULT 1 NOT NULL,
  MIGRATION_STATE VARCHAR2(24) DEFAULT 'legacy' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_USER_KEY_METADATA_MIGRATION_STATE
  ON USER_KEY_METADATA (MIGRATION_STATE);

ALTER TABLE USER_KEY_METADATA
  ADD CONSTRAINT FK_UKM_USER
  FOREIGN KEY (USER_ID)
  REFERENCES USERS(ID);
