-- User-scoped key metadata table (Phase 2 foundation)
-- NOTE: This script only creates metadata storage and does not alter existing encryption flows yet.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TABLES
  WHERE TABLE_NAME = 'USER_KEY_METADATA';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE USER_KEY_METADATA (
        USER_ID VARCHAR2(36) PRIMARY KEY,
        KDF_ALGO VARCHAR2(32) DEFAULT 'pbkdf2-sha256' NOT NULL,
        KDF_ITERATIONS NUMBER(10, 0) DEFAULT 310000 NOT NULL,
        KDF_SALT_HEX VARCHAR2(128) NOT NULL,
        WRAPPED_DEK_B64 CLOB NOT NULL,
        KEY_VERSION NUMBER(10, 0) DEFAULT 1 NOT NULL,
        MIGRATION_STATE VARCHAR2(24) DEFAULT 'legacy' NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_USER_KEY_METADATA_MIGRATION_STATE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_USER_KEY_METADATA_MIGRATION_STATE ON USER_KEY_METADATA (MIGRATION_STATE)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'FK_UKM_USER';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USER_KEY_METADATA ADD CONSTRAINT FK_UKM_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)';
  END IF;
END;
/
