-- Extend user key metadata for password rewrap and recovery-based forgot-password flow.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USER_KEY_METADATA' AND COLUMN_NAME = 'RECOVERY_WRAPPED_DEK_B64';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USER_KEY_METADATA ADD (RECOVERY_WRAPPED_DEK_B64 CLOB)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USER_KEY_METADATA' AND COLUMN_NAME = 'PASSWORD_EPOCH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USER_KEY_METADATA ADD (PASSWORD_EPOCH NUMBER(10, 0) DEFAULT 1 NOT NULL)';
  END IF;
END;
/
