-- Extend user key metadata for password rewrap and recovery-based forgot-password flow.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USER_KEY_METADATA' AND COLUMN_NAME = 'RECOVERY_WRAPPED_DEK_B64';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USER_KEY_METADATA ADD (RECOVERY_WRAPPED_DEK_B64 BLOB)';
  END IF;
END;
/

DECLARE
  v_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
BEGIN
  SELECT DATA_TYPE INTO v_type
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USER_KEY_METADATA' AND COLUMN_NAME = 'RECOVERY_WRAPPED_DEK_B64';

  IF v_type != 'BLOB' THEN
    RAISE_APPLICATION_ERROR(-20005, 'USER_KEY_METADATA.RECOVERY_WRAPPED_DEK_B64 phải là BLOB. Hãy reset schema để chuẩn hóa.');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USER_KEY_METADATA' AND COLUMN_NAME = 'PASSWORD_EPOCH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USER_KEY_METADATA ADD (PASSWORD_EPOCH NUMBER(10, 0) DEFAULT 1 NOT NULL)';
  END IF;
END;
/
