-- Email security columns + unified lock policy counters/state.

-- USERS: ensure EMAIL column exists and is BLOB in current model.
DECLARE
  v_count NUMBER;
  v_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'EMAIL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (EMAIL BLOB)';
  ELSE
    SELECT DATA_TYPE INTO v_type
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'EMAIL';

    IF v_type != 'BLOB' THEN
      RAISE_APPLICATION_ERROR(-20002, 'USERS.EMAIL phải là BLOB. Hãy chạy reset/migrate-seed mới nhất để chuẩn hóa schema email encrypted-only.');
    END IF;
  END IF;
END;
/

-- USERS: EMAIL_HASH
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'EMAIL_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (EMAIL_HASH VARCHAR2(64))';
  END IF;
END;
/

-- CUSTOMERS: ensure EMAIL column exists and is BLOB in current model.
DECLARE
  v_count NUMBER;
  v_type USER_TAB_COLUMNS.DATA_TYPE%TYPE;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'EMAIL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (EMAIL BLOB)';
  ELSE
    SELECT DATA_TYPE INTO v_type
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'EMAIL';

    IF v_type != 'BLOB' THEN
      RAISE_APPLICATION_ERROR(-20003, 'CUSTOMERS.EMAIL phải là BLOB. Hãy chạy reset/migrate-seed mới nhất để chuẩn hóa schema email encrypted-only.');
    END IF;
  END IF;
END;
/

-- CUSTOMERS: EMAIL_HASH
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'EMAIL_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (EMAIL_HASH VARCHAR2(64))';
  END IF;
END;
/

-- Drop obsolete columns if they still exist from older revisions.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'EMAIL_ENCRYPTED';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS DROP COLUMN EMAIL_ENCRYPTED';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'EMAIL_ENCRYPTED';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS DROP COLUMN EMAIL_ENCRYPTED';
  END IF;
END;
/

-- USERS: PASSWORD_FAILED_ATTEMPTS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'PASSWORD_FAILED_ATTEMPTS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USERS ADD (PASSWORD_FAILED_ATTEMPTS NUMBER(2, 0) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- USERS: PASSWORD_LOCKED
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'PASSWORD_LOCKED';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USERS ADD (PASSWORD_LOCKED NUMBER(1, 0) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- USERS: PASSWORD_LOCKED_AT
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'PASSWORD_LOCKED_AT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (PASSWORD_LOCKED_AT TIMESTAMP NULL)';
  END IF;
END;
/

-- USERS: LOCK_REASON
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'LOCK_REASON';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      q'[ALTER TABLE USERS ADD (LOCK_REASON VARCHAR2(32) DEFAULT 'NONE' NOT NULL)]';
  END IF;
END;
/

-- USERS: FORGOT_OTP_FAILED_ATTEMPTS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'FORGOT_OTP_FAILED_ATTEMPTS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USERS ADD (FORGOT_OTP_FAILED_ATTEMPTS NUMBER(2, 0) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

-- Constraints for new columns
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'CK_USERS_PASSWORD_LOCKED';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE USERS ADD CONSTRAINT CK_USERS_PASSWORD_LOCKED CHECK (PASSWORD_LOCKED IN (0, 1))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'CK_USERS_LOCK_REASON';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      q'[ALTER TABLE USERS ADD CONSTRAINT CK_USERS_LOCK_REASON CHECK (LOCK_REASON IN ('NONE', 'ADMIN', 'WRONG_PASSWORD', 'PIN_ATTEMPT', 'FORGOT_OTP_ATTEMPT'))]';
  END IF;
END;
/

-- Unique index by hash for fast lookup and uniqueness enforcement.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'UQ_USERS_EMAIL_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_USERS_EMAIL_HASH ON USERS(EMAIL_HASH)';
  END IF;
END;
/

-- Helpful lookup index for customer profile operations.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'IDX_CUSTOMERS_EMAIL_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CUSTOMERS_EMAIL_HASH ON CUSTOMERS(EMAIL_HASH)';
  END IF;
END;
/
