-- Add hash columns for phone/CCCD uniqueness and fast lookup.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'PHONE_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (PHONE_HASH VARCHAR2(64))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'CCCD_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (CCCD_HASH VARCHAR2(64))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'UQ_CUSTOMERS_PHONE_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_CUSTOMERS_PHONE_HASH ON CUSTOMERS(PHONE_HASH)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_INDEXES
  WHERE INDEX_NAME = 'UQ_CUSTOMERS_CCCD_HASH';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_CUSTOMERS_CCCD_HASH ON CUSTOMERS(CCCD_HASH)';
  END IF;
END;
/