-- Add compatibility columns for encrypted full name.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'FULL_NAME_ENC';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USERS ADD (FULL_NAME_ENC BLOB)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'CUSTOMERS' AND COLUMN_NAME = 'FULL_NAME_ENC';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMERS ADD (FULL_NAME_ENC BLOB)';
  END IF;
END;
/